version: "3.8"

services:

  accounts:
    image: tanubank/accounts
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tanubank-network
    
  loans:
    image: tanubank/loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tanubank-network
    
  cards:
    image: tanubank/cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tanubank-network
    
networks:
  tanubank-network: